Feature/generacion api
udistrital/ingresos_crud pull request #1
Opened 2022-06-09 20:34 UTC by brayanpasa99

Resuelve: udistrital/tesoreria_cliente#171

2022-06-15 05:45 UTC, AlexFBP requested changes
Solicitar
- A Seguridad (Mafe) configuracion en drone de sonarqube
- A Infraestructura (Jhon Freddy) configuración del repo, del websocket y demás actividades asociadas - Preparar las variables y sus valores adecuados para el despliegue en ambiente de pruebas
- A DBA (Jeisson) configuracion en drone de las variables de entorno para las migraciones, y confirmar si es posible ubicarla en:
  - db: udistrital_financiera
  - esquema: ingresos
  
  (Solicitar de paso visto bueno al script para la migración inicial, una vez ajustada de acuerdo a los comentarios)
  
Citar (en el Issue) los Ticket/tracker/kanban que haya sido necesario crear

2022-06-15 05:45 UTC, AlexFBP commented on main.go
> +	orm.Debug = true
Actualmente comentada en la L27 de este archivo, se puede descomentar allá y eliminar acá
```suggestion
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +// @Success 200 {object} models.AfectacionPresupuestal
```suggestion
// @Success 200 {object} []models.AfectacionPresupuestal
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +// @Success 201 {int} models.AfectacionPresupuestal
```suggestion
// @Success 201 {object} models.AfectacionPresupuestal
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +// @Param	id		path 	string	true		"The key for staticblock"
```suggestion
// @Param	id		path 	int	true		"The key for staticblock"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +// @Param	offset	query	string	false	"Start position of result set. Must be an integer"
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +// @Param	id		path 	string	true		"The id you want to update"
```suggestion
// @Param	id		path 	int	true		"The id you want to update"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +// @Success 200 {string} delete success!
```suggestion
// @Success 200 {object} map[string]interface{}
```

Se recomienda en la carpeta models agregar un archivo, digamos, `otros.go` cuyo contenido sea
```go
package models

type Eliminado struct {
  Id int
}
```
de tal manera que, en vez del primer suggested change, se pueda aplicar el siguiente:
```suggestion
// @Success 200 {object} models.Eliminado
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +		d := map[string]interface{}{"Id": id}
Continuando lo comentado en la L176 de este archivo, se podría aplicar lo siguiente:
```suggestion
		d := models.Eliminado{Id: id}
```
(Validar si lo anterior funciona)

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +// @Success 201 {int} models.Ingreso
```suggestion
// @Success 201 {object} models.Ingreso
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +// @Param	id		path 	string	true		"The key for staticblock"
```suggestion
// @Param	id		path 	int	true		"The key for staticblock"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +// @Success 200 {object} models.Ingreso
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
// @Success 200 {object} []models.Ingreso
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +// @Param	id		path 	string	true		"The id you want to update"
```suggestion
// @Param	id		path 	int	true		"The id you want to update"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +// @Success 200 {string} delete success!
De manera similar a la L176 de `controllers/afectacion_presupuestal.go`
```suggestion
// @Success 200 {object} models.Eliminado
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +		d := map[string]interface{}{"Id": id}
Similar a la L183 de `controllers/afectacion_presupuestal.go`
```suggestion
		d := models.Eliminado{Id: id}
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +// @Param	id		path 	string	true		"The id you want to delete"
```suggestion
// @Param	id		path 	int	true		"The id you want to delete"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/afectacion_presupuestal.go
> +// @Param	id		path 	string	true		"The id you want to delete"
```suggestion
// @Param	id		path 	int	true		"The id you want to delete"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/tipo_ingreso.go
> +// @Success 201 {int} models.TipoIngreso
```suggestion
// @Success 201 {object} models.TipoIngreso
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/tipo_ingreso.go
> +// @Param	id		path 	string	true		"The key for staticblock"
```suggestion
// @Param	id		path 	int	true		"The key for staticblock"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/tipo_ingreso.go
> +// @Success 200 {object} models.TipoIngreso
```suggestion
// @Param	limit	query	int	false	"Limit the size of result set. Must be an integer"
// @Param	offset	query	int	false	"Start position of result set. Must be an integer"
// @Success 200 {object} []models.TipoIngreso
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/tipo_ingreso.go
> +// @Param	id		path 	string	true		"The id you want to delete"
```suggestion
// @Param	id		path 	int	true		"The id you want to delete"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/tipo_ingreso.go
> +// @Param	id		path 	string	true		"The id you want to update"
```suggestion
// @Param	id		path 	int	true		"The id you want to update"
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/tipo_ingreso.go
> +// @Success 200 {string} delete success!
De manera similar a la L176 de `controllers/afectacion_presupuestal.go`
```suggestion
// @Success 200 {object} models.Eliminado
```

2022-06-15 05:45 UTC, AlexFBP commented on controllers/tipo_ingreso.go
> +		d := map[string]interface{}{"Id": id}
Similar a la L183 de `controllers/afectacion_presupuestal.go`
```suggestion
		d := models.Eliminado{Id: id}
```

2022-06-15 05:45 UTC, AlexFBP commented on models/afectacion_presupuestal.go
> +	FechaModificacion time.Time `orm:"column(fecha_modificacion);type(timestamp without time zone)"`
Varios...
- Id: (De ser necesario) Agregar `;auto` - Validar primero con el POST, hacerlo **sin** el `Id` en el objeto a enviar en el POST
- Para las fechas, usar `timestamp with time zone` (y ajustar pgmodeler y migracion)
- Para las fechas (y, de ser necesario, ajustar también el pgmodeler y la migracion)
  - creacion: (de ser necesario) agregar `;auto_now_add;type(datetime)` - validar si se requiere quitando el `FechaCreacion` del objeto del POST
  - modificacion: (de ser necesario) agregar `;auto_now;type(datetime)` - validar si se requiere quitando ambas fechas en el PUT/PATCH
  - En ambos casos, validar que las fechas pasadas en el body sean ignoradas o se puedan pasar quitandolas del body, dado que las fechas las debería generar este helper/model

Referencia: [Documentación Beego](https://beego.vip/docs/mvc/model/models.md)

2022-06-15 05:45 UTC, AlexFBP commented on models/ingreso.go
> +}
Proceder de manera similar a lo comentado en las L14-19 de `models/afectacion_presupuestal.go`

2022-06-15 05:45 UTC, AlexFBP commented on models/tipo_ingreso.go
> +}
- Adicional a lo comentado en las L14-19 de `models/afectacion_presupuestal.go`...
- Si `ParametrizacionContable` es jsonb, falta agregarle `;type(jsonb)`
- Adicionalmente, esta es una tabla paramétrica, ver [lineamientos adicionales a la fecha](https://github.com/udistrital/lineamientos_oas/blob/f6ba29cff0e597874cc0ae1d23830a2dc759b729/modelo_de_datos/estandar.md#tablas-tipo-cat%C3%A1logo-o-param%C3%A9tricas) (Confirmar con DBA - Jeisson si se puede prescindir, de acuerdo a lo anterior; de los campos de fecha) - Resumen:
  - Faltaría `numero_orden` (sugeriría llamarlo `peso`)
  - Fataría `codigo_abreviacion`(sugeriría llamarlo `sigla`) y agregar una restricción unique a este campo

Referencia adicional: [documentación Beego](https://beego.vip/docs/mvc/model/models.md#postgresql)

2022-06-15 05:45 UTC, AlexFBP commented on models/ingreso.go
> +	Metadatos            string       `orm:"column(metadatos);null"`
Si `Metadatos` es jsonb, falta agregarle `;type(jsonb)`

2022-06-15 05:45 UTC, AlexFBP commented on template.env
> +export INGRESOS_CRUD_HTTP_PORT=8080
- Ajustar el README para que mencione este archivo
- (De paso) Ajustar la sección models para que tenga los links al svg/dbm

2022-06-15 05:45 UTC, AlexFBP commented on controllers/ingreso.go
> +	"github.com/astaxie/beego/logs"
Invertir...
```suggestion
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/logs"

	"github.com/udistrital/ingresos_crud/models"
```

2022-06-15 05:45 UTC, AlexFBP commented on database/scripts/20220609_141721_inicial_up.sql
> +-- ddl-end --
Falta documentación a nivel de tablas y columnas...
Agregar comentarios como mínimo en las columnas destinadas a guardar IDs de otras DB/esquemas, pero si de paso se pueden agregar comentarios a las demas tablas y/o columnas, mejor
Hacerlo desde el pgmodeler y exportar/ajustar la migración nuevamente
(De paso, validar en local el `bee migrate rollback`)

2022-06-15 05:45 UTC, AlexFBP commented on database/scripts/20220609_141721_inicial_up.sql
> +SET search_path TO pg_catalog,public,ingresos;
Revisar si con lo siguiente sigue funcionando:
```suggestion
SET search_path TO public,ingresos;
```

2022-06-15 05:45 UTC, AlexFBP commented on swagger/swagger.json
> +{
Una vez ajustados los controllers, poner a correr la API y/o `bee generate docs` para que se actualice este y el `swagger.yml`

2022-06-16 22:46 UTC, brayanpasa99 commented on models/afectacion_presupuestal.go
> +	FechaModificacion time.Time `orm:"column(fecha_modificacion);type(timestamp without time zone)"`
Respuesta:

1. Si es necesario el auto o agrega Id con 0 y además genera problemas de integridad
2. Se agustó pgModeler y migración con timestamptz
3. Se agregan respectivamente los campos auto_now, auto_now_add y type(datetime) dado que al enviar sin esos parámetros envía restricción de nulidad
4. Con lo anterior en mente se hizo la prueba sin enviar fechas e id en el body y se genera/actualiza correctamente

Se hará similar con todas.

2022-06-16 22:46 UTC, brayanpasa99 commented on models/tipo_ingreso.go
> +}
Jeisson confirma que se puede prescindir de esos datos si el usuario final no va a tener contacto con la tabla, sin embargo, creo que se pueden crear Tipos de Ingreso y quizá se pida que se parametrice para que el usuario pueda modifcarlos, considero en ese orden de ideas dejar los campos de fecha.

Ahora, con respecto al campo numero_orden y codigo_abreviación, Jeisson indica que se deben dejar con el nombre original para facilitar el entendimiento.

Con lo primero en mente no sé si sea necesario agregar campo de descripción, numero_orden y codigo_abreviacion, espero confirmación para saber cómo sería la forma final de la tabla.

2022-06-17 08:30 UTC, AlexFBP requested changes
Un ajuste menor y quedaría

2022-06-17 08:30 UTC, AlexFBP commented on README.md
> +<img src="database/ingresos.svg" />
```suggestion
![Esquema Ingresos](database/ingresos.svg)
```

2022-06-22 01:48 UTC, AlexFBP approved these changes

2022-06-22 01:48 UTC, merged